BATIAI-528 - Updating vpc module to add s3 endpoint
CMS-Enterprise/batcave-tf-vpc pull request #27
Opened 2023-08-08 17:56 UTC by sshaikRC

## Fixes Issue: [link to JIRA ticket](http://example.com)

## Description:

## Security Impact Analysis Questionnaire
### Submitter Checklist
-  [ ] Is there an impact on Auditing and Logging procedures or capabilities?
-  [ ] Is there an impact on Authentication procedures or capabilities?
-  [ ] Is there an impact on Authorization procedures or capabilities?
-  [ ] Is there an impact on Communication Security procedures or capabilities?
-  [ ] Is there an impact on Cryptography procedures or capabilities?
-  [ ] Is there an impact on Sensitive Data procedures or capabilities?
-  [ ] Is there an impact on any other security-related procedures or capabilities?
-  [x] No security impacts identified.

Security Risks Identified - For any applicable items on the "Submitter Checklist," describe the impact of the change and any implemented mitigations.

2023-08-08 18:03 UTC, robo-gotham commented
Snyk Scanning for Commit: 41bb2d2abf133524540144afea67fb695311bd38

Snyk Infrastructure as Code

- Snyk testing Infrastructure as Code configuration issues.
✔ Test completed.

Issues

<details><summary>Medium Severity Issues: 1</summary>

  [Medium] Access policy is not attached to the endpoint
  Info:    Access policy is not attached to the endpoint. By default endpoints
           have no access controls applied which means anyone within account can
           access them
  Rule:    https://security.snyk.io/rules/cloud/SNYK-CC-AWS-428
  Path:    resource > aws_vpc_endpoint[s3]
  File:    main.tf
  Resolve: Set `policy` attribute

-------------------------------------------------------

</details>

Test Summary

  Organization: batcave-ispg
  Project name: CMS-Enterprise/batcave-tf-vpc

✔ Files without issues: 2
✗ Files with issues: 1
  Ignored issues: 0
  Total issues: 1 [ 0 critical, 0 high, 1 medium, 0 low ]

-------------------------------------------------------

Report Complete

  Your test results are available at: https://snyk.io/org/batcave-ispg/projects
  under the name: CMS-Enterprise/batcave-tf-vpc

2023-08-15 13:53 UTC, bushong1 requested changes

2023-08-15 13:53 UTC, bushong1 commented on main.tf
> +}
I don't think this will work.  You're creating a route table out of whole-cloth instead of reusing the route tables that are already attached to the subnets.  Lets figure out how to look them up with data resources, or maybe the data is already there in our subnet resources.

2023-08-15 13:53 UTC, bushong1 commented on main.tf
> +
We'll want to make this conditional so we can disable it in dev and not have 1 of these for each dev cluster on an account.  A var for `create_s3_vpc_endpoint`

2023-08-15 13:53 UTC, bushong1 commented on main.tf
> +    Name = "batcave-dev-s3-endpoint"
```suggestion
    Name = "${var.cluster_name}-s3-endpoint"
```

2023-08-15 13:53 UTC, bushong1 commented on main.tf
> +  nat_gateway_id            = "nat-0dc7d0fafd6d5336b"
Look this up with a data resource.

2023-08-15 13:53 UTC, bushong1 commented on main.tf
> +}
Why did you move this?

2023-08-15 17:40 UTC, bushong1 commented on main.tf
> +}
Disregard

2023-08-16 19:30 UTC, bushong1 approved these changes

2023-08-16 19:31 UTC, merged